// Generated by gencpp from file sos_fusion/PointArray.msg
// DO NOT EDIT!


#ifndef SOS_FUSION_MESSAGE_POINTARRAY_H
#define SOS_FUSION_MESSAGE_POINTARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace sos_fusion
{
template <class ContainerAllocator>
struct PointArray_
{
  typedef PointArray_<ContainerAllocator> Type;

  PointArray_()
    : header()
    , cluster_center()
    , cluster_min()
    , cluster_max()  {
    }
  PointArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cluster_center(_alloc)
    , cluster_min(_alloc)
    , cluster_max(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _cluster_center_type;
  _cluster_center_type cluster_center;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _cluster_min_type;
  _cluster_min_type cluster_min;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _cluster_max_type;
  _cluster_max_type cluster_max;





  typedef boost::shared_ptr< ::sos_fusion::PointArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sos_fusion::PointArray_<ContainerAllocator> const> ConstPtr;

}; // struct PointArray_

typedef ::sos_fusion::PointArray_<std::allocator<void> > PointArray;

typedef boost::shared_ptr< ::sos_fusion::PointArray > PointArrayPtr;
typedef boost::shared_ptr< ::sos_fusion::PointArray const> PointArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sos_fusion::PointArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sos_fusion::PointArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sos_fusion::PointArray_<ContainerAllocator1> & lhs, const ::sos_fusion::PointArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cluster_center == rhs.cluster_center &&
    lhs.cluster_min == rhs.cluster_min &&
    lhs.cluster_max == rhs.cluster_max;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sos_fusion::PointArray_<ContainerAllocator1> & lhs, const ::sos_fusion::PointArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sos_fusion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sos_fusion::PointArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sos_fusion::PointArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sos_fusion::PointArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sos_fusion::PointArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sos_fusion::PointArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sos_fusion::PointArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sos_fusion::PointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2fe739f074abe7938c339e74128b9b77";
  }

  static const char* value(const ::sos_fusion::PointArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2fe739f074abe793ULL;
  static const uint64_t static_value2 = 0x8c339e74128b9b77ULL;
};

template<class ContainerAllocator>
struct DataType< ::sos_fusion::PointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sos_fusion/PointArray";
  }

  static const char* value(const ::sos_fusion::PointArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sos_fusion::PointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Point[] cluster_center\n"
"geometry_msgs/Point[] cluster_min\n"
"geometry_msgs/Point[] cluster_max\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::sos_fusion::PointArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sos_fusion::PointArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cluster_center);
      stream.next(m.cluster_min);
      stream.next(m.cluster_max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sos_fusion::PointArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sos_fusion::PointArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cluster_center[]" << std::endl;
    for (size_t i = 0; i < v.cluster_center.size(); ++i)
    {
      s << indent << "  cluster_center[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.cluster_center[i]);
    }
    s << indent << "cluster_min[]" << std::endl;
    for (size_t i = 0; i < v.cluster_min.size(); ++i)
    {
      s << indent << "  cluster_min[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.cluster_min[i]);
    }
    s << indent << "cluster_max[]" << std::endl;
    for (size_t i = 0; i < v.cluster_max.size(); ++i)
    {
      s << indent << "  cluster_max[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.cluster_max[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOS_FUSION_MESSAGE_POINTARRAY_H
